[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies]
polars = { version = "0.37", features = ["csv-file"] }
linfa = "0.6.1"
linfa-trees = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.15"
